export * from './about-page/about-page'
export * from './cart-page/cart-page'
export * from './faq-page/faq-page'
export * from './footer-page/footer-page'
// export * from './home-page/home-page'
export * from './landing-page/landing-page/home-page'
export * from './landing-page/landing-page'
export * from './menu-page/menu-page'
export * from './order-complete/order-complete'
export * from './order-flow/order-flow'
export * from './order-page/order-page'
export * from './order-prepare/order-prepare'
export * from './profile-page/profile-page'
export * from './payment-page/t-payment'
export * from './productadd-page/productadd'
export * from './profile-page/profile-page'
export * from './setting-page/setting-page'
export * from './tapn\'taste flow/contact-page/contact-page'
export * from './tapn\'taste flow/payment-screen/payment-screen'
export * from './tapn\'taste flow/payment-success/payment-success'
export * from './tapn\'taste flow/booking-confirmation/booking-confirmation'
export * from './tapn\'taste flow/order-placed-screen/order-placed-screen'
export * from './restaurant-page/restaurant-list'