[build]
  # Set the base directory for your build (for example, if the app is under 'dist')
  base = "/"

[[redirects]]
  from = "/*"
  to = "/dist/t-scanning/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/dist/t-admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/tap-n-taste-api/*"
  to = "/tap-n-taste-api/main.js"
  status = 200
  force = true
